using AiAssistant.Models.Responses;
using AiAssistant.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace AiAssistant.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class AiDashboardController : ControllerBase
    {
        private readonly IAiDashboardService _aiDashboardService;
        private readonly ILogger<AiDashboardController> _logger;

        public AiDashboardController(IAiDashboardService aiDashboardService, ILogger<AiDashboardController> logger)
        {
            _aiDashboardService = aiDashboardService;
            _logger = logger;
        }

        /// <summary>
        /// Generate dashboard from a question
        /// POST /api/dashboard/generate-forecast
        /// </summary>
        [HttpPost("generate-forecast")]
        [ProducesResponseType(typeof(GenerateDashboardResponse), StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<IActionResult> GenerateDashboard([FromBody] GenerateDashboardRequest request)
        {
            if (string.IsNullOrWhiteSpace(request?.Question))
            {
                return BadRequest(new
                {
                    error = "Validation failed",
                    message = "Question cannot be empty"
                });
            }

            try
            {
                _logger.LogInformation("Generating dashboard for question: {Question}", request.Question);

                var dashboard = await _aiDashboardService.GenerateDashboardAsync(request.Question);

                return Ok(dashboard);
            }
            catch (InvalidOperationException ex)
            {
                _logger.LogError(ex, "Invalid operation while generating dashboard");
                return StatusCode(500, new
                {
                    error = "Dashboard generation failed",
                    message = ex.Message
                });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error generating dashboard");
                return StatusCode(500, new
                {
                    error = "Internal server error",
                    message = ex.Message
                });
            }
        }


        /// <summary>
        /// NEW: Auto-generate complete dashboard with 4 AI-generated questions
        /// Each question gets data and creates visualization (chart, progress, pie, etc.)
        /// POST /api/dashboard/auto-generate
        /// </summary>
        [HttpPost("auto-generate")]
        [ProducesResponseType(typeof(AutoDashboardResponse), StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<IActionResult> AutoGenerateDashboard([FromBody] AutoDashboardRequest? request = null)
        {
            try
            {
                var context = request?.Context ?? "WMS operations and warehouse management";
                _logger.LogInformation("Auto-generating dashboard with context: {Context}", context);

              var dashboard = await _aiDashboardService.GenerateAutoDashboardAsync(context);

                return Ok(dashboard);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error auto-generating dashboard");
                return StatusCode(500, new
                {
                    error = "Auto-dashboard generation failed",
                    message = ex.Message,
                    details = ex.StackTrace
                });
            }
        }
    }

    public class AutoDashboardRequest
    {
        public string? Context { get; set; }
    }

    public class GenerateDashboardRequest
    {
        public string Question { get; set; } = string.Empty;
    }

    public class AutoDashboardResponse
    {
        public string Title { get; set; } = "";
        public string Description { get; set; } = "";
        public List<string> Questions { get; set; } = new();
        public List<object> Widgets { get; set; } = new();
        public DateTime GeneratedAt { get; set; }
        public int TotalDataPoints { get; set; }
    }

    public class GenerateDashboardResponse
    {
        public string Title { get; set; } = "";
        public string Description { get; set; } = "";
        public string Question { get; set; } = "";
        public object Widget { get; set; } = new();
        public DateTime GeneratedAt { get; set; }
        public int DataPoints { get; set; }
        public bool IsAiGenerated { get; set; }
    }
}
