version: "3.8"
services:
  api_gateway:
    build:
      context: .
      dockerfile: ./BS-API-Secure/ApiGateway/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Bangkok
      - SERVERDB_SECURITY=Server=10.10.60.60;Database=Timesheet;user id=sa;password=Local@dmin;Encrypt=False;TrustServerCertificate=True;Integrated Security=False;
      - ISSUER_SIGIN_KEY=LqpOSpdD9FpngQnVzunOxe4hnxXdoN99bnYld4Pc16I=
      - VALID_ISSUER=http://10.10.60.188
      - VALID_AUDIENCE=http://10.10.60.188
      - ALLOWIP_WEB=*
      - KEY_WEB=API_KEY_WEB
    networks:
      - internal
    restart: always
  auth_api:
    build:
      context: .
      dockerfile: ./BS-API-Secure/Authentication/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    environment:
      - TZ=Asia/Bangkok
      - ASPNETCORE_ENVIRONMENT=Production
      - SERVERDB=Server=10.10.60.60;Database=Timesheet;user id=sa;password=Local@dmin;Encrypt=False;TrustServerCertificate=True;Integrated Security=False;
      - SERVERDB_SECURITY=Server=10.10.60.60;Database=Timesheet;user id=sa;password=Local@dmin;Encrypt=False;TrustServerCertificate=True;Integrated Security=False;
      - ISSUER_SIGIN_KEY=LqpOSpdD9FpngQnVzunOxe4hnxXdoN99bnYld4Pc16I=
      - VALID_ISSUER=http://10.10.60.188
      - VALID_AUDIENCE=http://10.10.60.188
      - EXPIRES=15
      - REFRESH=30
      - ACCESS_FAILURE_LIMIT=5
      - ALLOWIP_WEB=*
      - KEY_WEB=API_KEY_WEB
      - DB_SCHEMA=sec
      - USERNAME_ADMIN=Wau7MCRQswc=
    networks:
      - internal
    restart: always
  bs_core_api:
    build:
      context: .
      dockerfile: ./BS-API-Core/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    environment:
      - TZ=Asia/Bangkok
      - ASPNETCORE_ENVIRONMENT=Production
      - SERVERDB=Server=10.10.60.60;Database=Timesheet;user id=sa;password=Local@dmin;Encrypt=False;TrustServerCertificate=True;Integrated Security=False;
      - SERVERDB_SECURITY=Server=10.10.60.60;Database=Timesheet;user id=sa;password=Local@dmin;Encrypt=False;TrustServerCertificate=True;Integrated Security=False;
      - ISSUER_SIGIN_KEY=LqpOSpdD9FpngQnVzunOxe4hnxXdoN99bnYld4Pc16I=
      - VALID_ISSUER=http://10.10.60.188
      - VALID_AUDIENCE=http://10.10.60.188
      - EXPIRES=15
      - REFRESH=30
      - ACCESS_FAILURE_LIMIT=5
      - ALLOWIP_WEB=*
      - KEY_WEB=API_KEY_WEB
      - DB_SCHEMA=sec
      - USERNAME_ADMIN=Wau7MCRQswc=
    networks:
      - internal
    restart: always
  bs_import_export_manager:
    build:
      context: .
      dockerfile: ./BS-Import-Export-Manager/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    environment:
      - TZ=Asia/Bangkok
      - ASPNETCORE_ENVIRONMENT=Production
      - DATABASE_CONNECTION=Server=10.10.60.60;Database=Timesheet;User Id=sa;Password=Local@dmin;Encrypt=False;TrustServerCertificate=True;
      - SERVERDB=Server=10.10.60.60;Database=Timesheet;user id=sa;password=Local@dmin;Encrypt=False;TrustServerCertificate=True;Integrated Security=False;
      - SERVERDB_SECURITY=Server=10.10.60.60;Database=Timesheet;user id=sa;password=Local@dmin;Encrypt=False;TrustServerCertificate=True;Integrated Security=False;
      - ISSUER_SIGIN_KEY=LqpOSpdD9FpngQnVzunOxe4hnxXdoN99bnYld4Pc16I=
      - VALID_ISSUER=http://10.10.60.188
      - VALID_AUDIENCE=http://10.10.60.188
      - EXPIRES=15
      - REFRESH=30
      - ACCESS_FAILURE_LIMIT=5
      - ALLOWIP_WEB=*
      - KEY_WEB=API_KEY_WEB
      - DB_SCHEMA=sec
      - USERNAME_ADMIN=Wau7MCRQswc=
    networks:
      - internal
    restart: always
  bs_notification:
    build:
      context: .
      dockerfile: ./BS-Notification/Notification/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
        - "8081:8080"
    environment:
        - TZ=Asia/Bangkok
        - ASPNETCORE_ENVIRONMENT=Production
        - DATABASE_CONNECTION=Server=10.10.60.60;Database=Timesheet;User Id=sa;Password=Local@dmin;Encrypt=False;TrustServerCertificate=True;
        - SERVERDB=Server=10.10.60.60;Database=Timesheet;user id=sa;password=Local@dmin;Encrypt=False;TrustServerCertificate=True;Integrated Security=False;
        - SERVERDB_SECURITY=Server=10.10.60.60;Database=Timesheet;user id=sa;password=Local@dmin;Encrypt=False;TrustServerCertificate=True;Integrated Security=False;
        - ISSUER_SIGIN_KEY=LqpOSpdD9FpngQnVzunOxe4hnxXdoN99bnYld4Pc16I=
        - VALID_ISSUER=http://10.10.60.188
        - VALID_AUDIENCE=http://10.10.60.188
        - EXPIRES=15
        - REFRESH=30
        - ACCESS_FAILURE_LIMIT=5
        - ALLOWIP_WEB=*
        - KEY_WEB=API_KEY_WEB
        - DB_SCHEMA=sec
        - USERNAME_ADMIN=Wau7MCRQswc=
    networks:
      - internal
    restart: always
networks:
  internal:
    driver: bridge
