const Config = {
  API_URL: process.env.REACT_APP_API_URL,
  OMS_API_URL: process.env.REACT_APP_OMS_API_URL || "/api",
  FRONTEND_BASE_URL: process.env.REACT_APP_FRONTEND_BASE_URL || window.location.origin,
  OAUTH_CALLBACK_BASE_URL: process.env.REACT_APP_OAUTH_CALLBACK_BASE_URL || "",
  WEBHOOK_BASE_URL: process.env.REACT_APP_WEBHOOK_BASE_URL || "",
  AUTH_API_URL: process.env.REACT_APP_AUTH_API_URL,
  IMPORT_API_URL: process.env.REACT_APP_IMPORT_API_URL,
  CORE_DIRECT_URL: process.env.REACT_APP_CORE_DIRECT_URL,
  MOBILE_DIRECT_URL: process.env.REACT_APP_MOBILE_DIRECT_URL,
  LICENSE_KEY: process.env.REACT_APP_API_LICENSE_KEY,
  ENCRYPYION: process.env.REACT_APP_ENCRYPYION,
  APP_NAME: process.env.REACT_APP_NAME,
  BASE_URL: process.env.REACT_APP_BASE_URL,
  API_NOTIFY: process.env.REACT_APP_NOTIFY_URL,
  REPORT_VIEWER_URL: process.env.REACT_APP_REPORT_VIEWER_URL,
  APP_ENV: process.env.REACT_APP_ENV,
  SCALE: process.env.REACT_APP_DECIMAL_PLACES
};

export default Config;
