// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmsApi.Extensions;

#nullable disable

namespace OmsApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261001052154_AddPlatformWebhookEvents")]
    partial class AddPlatformWebhookEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformCredential", b =>
                {
                    b.Property<long>("PlatformCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("platform_credential_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PlatformCredentialId"));

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("access_token_encrypted");

                    b.Property<DateTime>("AccessTokenExpiresDate")
                        .HasColumnType("datetime")
                        .HasColumnName("access_token_expires_date");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("create_date");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("YES")
                        .HasColumnName("is_active");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastRefreshDate")
                        .HasColumnType("datetime")
                        .HasColumnName("last_refresh_date");

                    b.Property<DateTime?>("LastUseDate")
                        .HasColumnType("datetime")
                        .HasColumnName("last_use_date");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("platform");

                    b.Property<string>("RefreshTokenEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("refresh_token_encrypted");

                    b.Property<DateTime?>("RefreshTokenExpiresDate")
                        .HasColumnType("datetime")
                        .HasColumnName("refresh_token_expires_date");

                    b.Property<string>("RequiresReauthorization")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("NO")
                        .HasColumnName("requires_reauthorization");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("shop_id");

                    b.Property<string>("ShopName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("shop_name");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date");

                    b.HasKey("PlatformCredentialId")
                        .HasName("PK_t_oms_platform_credential");

                    b.HasIndex("Platform", "ShopId")
                        .IsUnique()
                        .HasDatabaseName("UQ_t_oms_platform_credential_platform_shop");

                    b.ToTable("t_oms_platform_credential", "oms");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformDocument", b =>
                {
                    b.Property<long>("PlatformDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("platform_document_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PlatformDocumentId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("create_date");

                    b.Property<string>("DocumentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("document_status");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileChecksum")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("file_checksum");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastPrintDate")
                        .HasColumnType("datetime")
                        .HasColumnName("last_print_date");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("platform");

                    b.Property<string>("PlatformOrderId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_order_id");

                    b.Property<string>("PlatformPackageId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_package_id");

                    b.Property<string>("PlatformRequestId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_request_id");

                    b.Property<int>("PrintCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("print_count");

                    b.Property<string>("PrintStorageKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("print_storage_key");

                    b.Property<string>("RawStorageKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("raw_storage_key");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("shop_id");

                    b.Property<string>("SourceContentType")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("source_content_type");

                    b.Property<DateTime?>("SourceExpiresDate")
                        .HasColumnType("datetime")
                        .HasColumnName("source_expires_date");

                    b.Property<string>("SourceFormat")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("source_format");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("tracking_number");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date");

                    b.HasKey("PlatformDocumentId")
                        .HasName("PK_t_oms_platform_document");

                    b.HasIndex("Platform", "ShopId", "PlatformOrderId", "PlatformPackageId", "DocumentType")
                        .IsUnique()
                        .HasDatabaseName("UQ_t_oms_platform_document_package")
                        .HasFilter("[platform_package_id] IS NOT NULL");

                    b.ToTable("t_oms_platform_document", "oms");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformOrder", b =>
                {
                    b.Property<long>("OrderRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_record_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderRecordId"));

                    b.Property<string>("BuyerName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("buyer_name");

                    b.Property<string>("BuyerRemarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("buyer_remarks");

                    b.Property<DateTime?>("CancellationDeadline")
                        .HasColumnType("datetime")
                        .HasColumnName("cancellation_deadline");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("create_date");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("THB")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("EstimatedDeliveryDate")
                        .HasColumnType("datetime")
                        .HasColumnName("estimated_delivery_date");

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("datetime")
                        .HasColumnName("last_sync_date");

                    b.Property<DateTime>("OrderCreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("order_created_date");

                    b.Property<DateTime?>("OrderUpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("order_updated_date");

                    b.Property<string>("OriginalStatus")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("original_status");

                    b.Property<string>("PackageNumber")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("package_number");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("platform");

                    b.Property<string>("PlatformOrderId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_order_id");

                    b.Property<string>("RecipientAddressLine1")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("recipient_address_line1");

                    b.Property<string>("RecipientAddressLine2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("recipient_address_line2");

                    b.Property<string>("RecipientCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(2)")
                        .HasDefaultValue("TH")
                        .HasColumnName("recipient_country");

                    b.Property<string>("RecipientDistrict")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("recipient_district");

                    b.Property<string>("RecipientFullAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("recipient_full_address");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("RecipientPhone")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("recipient_phone");

                    b.Property<string>("RecipientPostalCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("recipient_postal_code");

                    b.Property<string>("RecipientProvince")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("recipient_province");

                    b.Property<string>("RecipientSubDistrict")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("recipient_sub_district");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<string>("ShippingCarrier")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("shipping_carrier");

                    b.Property<decimal?>("ShippingFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("shipping_fee");

                    b.Property<string>("ShippingMethod")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("shipping_method");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("shop_id");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("shop_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("SYNCED")
                        .HasColumnName("sync_status");

                    b.Property<string>("TaxInvoiceAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("tax_invoice_address");

                    b.Property<string>("TaxInvoiceBranchCode")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tax_invoice_branch_code");

                    b.Property<string>("TaxInvoiceCompanyName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("tax_invoice_company_name");

                    b.Property<bool>("TaxInvoiceRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("tax_invoice_requested");

                    b.Property<string>("TaxInvoiceTaxId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("tax_invoice_tax_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("tracking_number");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date");

                    b.HasKey("OrderRecordId")
                        .HasName("PK_t_oms_order");

                    b.HasIndex("Status", "OrderCreatedDate")
                        .HasDatabaseName("IX_t_oms_order_status");

                    b.HasIndex("Platform", "ShopId", "OrderCreatedDate")
                        .HasDatabaseName("IX_t_oms_order_shop");

                    b.HasIndex("Platform", "ShopId", "PlatformOrderId")
                        .IsUnique()
                        .HasDatabaseName("UQ_t_oms_order_platform_order");

                    b.ToTable("t_oms_order", "oms");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformOrderItem", b =>
                {
                    b.Property<long>("OrderItemRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_item_record_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderItemRecordId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("create_date");

                    b.Property<decimal>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("image_url");

                    b.Property<string>("ItemName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("item_name");

                    b.Property<long?>("ModelId")
                        .HasColumnType("bigint")
                        .HasColumnName("model_id");

                    b.Property<long>("OrderRecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_record_id");

                    b.Property<string>("PlatformItemId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_item_id");

                    b.Property<long?>("PlatformOrderItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("platform_order_item_id");

                    b.Property<long?>("PromotionGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("promotion_group_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<string>("Sku")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("sku");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date");

                    b.Property<string>("Variation")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("variation");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("weight");

                    b.HasKey("OrderItemRecordId")
                        .HasName("PK_t_oms_order_item");

                    b.HasIndex("OrderRecordId")
                        .HasDatabaseName("IX_t_oms_order_item_order");

                    b.ToTable("t_oms_order_item", "oms");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformPackage", b =>
                {
                    b.Property<long>("PlatformPackageRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("platform_package_record_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PlatformPackageRecordId"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<int>("BoxNumber")
                        .HasColumnType("int")
                        .HasColumnName("box_number");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("create_date");

                    b.Property<string>("CustomerOrderNumber")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("customer_order_number");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("datetime")
                        .HasColumnName("last_sync_date");

                    b.Property<long?>("OrderRecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_record_id");

                    b.Property<Guid>("OutboundOrderMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outbound_order_master_id");

                    b.Property<Guid>("OutboundSortMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outbound_sort_master_id");

                    b.Property<string>("PackageStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("package_status");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("platform");

                    b.Property<string>("PlatformOrderId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_order_id");

                    b.Property<string>("PlatformPackageId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_package_id");

                    b.Property<string>("RequestId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("request_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<string>("ShippingProviderId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("shipping_provider_id");

                    b.Property<string>("ShippingProviderName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("shipping_provider_name");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("shop_id");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("sync_status");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("tracking_number");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date");

                    b.HasKey("PlatformPackageRecordId")
                        .HasName("PK_t_oms_platform_package");

                    b.HasIndex("OrderRecordId")
                        .HasDatabaseName("IX_t_oms_platform_package_order_record");

                    b.HasIndex("SyncStatus", "LastSyncDate")
                        .HasDatabaseName("IX_t_oms_platform_package_sync");

                    b.HasIndex("Platform", "ShopId", "OutboundSortMasterId")
                        .IsUnique()
                        .HasDatabaseName("UQ_t_oms_platform_package_wms");

                    b.HasIndex("Platform", "ShopId", "PlatformPackageId")
                        .HasDatabaseName("IX_t_oms_platform_package_platform_id")
                        .HasFilter("[platform_package_id] IS NOT NULL");

                    b.HasIndex("Platform", "ShopId", "PlatformOrderId", "BoxNumber")
                        .HasDatabaseName("IX_t_oms_platform_package_order");

                    b.ToTable("t_oms_platform_package", "oms");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformPackageItem", b =>
                {
                    b.Property<long>("PlatformPackageItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("platform_package_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PlatformPackageItemId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("create_date");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("item_number");

                    b.Property<string>("PlatformItemId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_item_id");

                    b.Property<long>("PlatformPackageRecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("platform_package_record_id");

                    b.Property<string>("PlatformSkuId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_sku_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date");

                    b.Property<Guid>("WmsItemMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wms_item_master_id");

                    b.HasKey("PlatformPackageItemId")
                        .HasName("PK_t_oms_platform_package_item");

                    b.HasIndex("PlatformPackageRecordId", "ItemNumber")
                        .HasDatabaseName("IX_t_oms_platform_package_item_package");

                    b.ToTable("t_oms_platform_package_item", "oms");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformSyncLog", b =>
                {
                    b.Property<long>("SyncLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sync_log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SyncLogId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("create_date");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int")
                        .HasColumnName("duration_ms");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("platform");

                    b.Property<string>("RequestPayload")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("request_payload");

                    b.Property<string>("ShopId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("shop_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.Property<string>("SyncSource")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("sync_source");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("sync_status");

                    b.Property<string>("SyncType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("ORDER")
                        .HasColumnName("sync_type");

                    b.Property<int>("TotalFailed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_failed");

                    b.Property<int>("TotalFetched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_fetched");

                    b.Property<int>("TotalInserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_inserted");

                    b.Property<int>("TotalUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_updated");

                    b.HasKey("SyncLogId")
                        .HasName("PK_t_oms_sync_log");

                    b.HasIndex("SyncStatus", "StartDate")
                        .HasDatabaseName("IX_t_oms_sync_log_status");

                    b.HasIndex("Platform", "ShopId", "StartDate")
                        .HasDatabaseName("IX_t_oms_sync_log_platform_shop");

                    b.ToTable("t_oms_sync_log", "oms");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformSyncLogDetail", b =>
                {
                    b.Property<long>("SyncLogDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sync_log_detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SyncLogDetailId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("create_date");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("message");

                    b.Property<string>("NewStatus")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("new_status");

                    b.Property<string>("OldStatus")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("old_status");

                    b.Property<long?>("OrderRecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_record_id");

                    b.Property<string>("PlatformOrderId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_order_id");

                    b.Property<long>("SyncLogId")
                        .HasColumnType("bigint")
                        .HasColumnName("sync_log_id");

                    b.HasKey("SyncLogDetailId")
                        .HasName("PK_t_oms_sync_log_detail");

                    b.HasIndex("SyncLogId")
                        .HasDatabaseName("IX_t_oms_sync_log_detail_log");

                    b.HasIndex("PlatformOrderId", "CreateDate")
                        .HasDatabaseName("IX_t_oms_sync_log_detail_order");

                    b.ToTable("t_oms_sync_log_detail", "oms");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformWebhookEvent", b =>
                {
                    b.Property<long>("WebhookEventRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("webhook_event_record_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WebhookEventRecordId"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasColumnName("event_key");

                    b.Property<DateTime?>("EventTime")
                        .HasColumnType("datetime")
                        .HasColumnName("event_time");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("event_type");

                    b.Property<string>("InternalStatus")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("internal_status");

                    b.Property<DateTime?>("LastAttemptDate")
                        .HasColumnType("datetime")
                        .HasColumnName("last_attempt_date");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("platform");

                    b.Property<string>("PlatformOrderId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_order_id");

                    b.Property<string>("PlatformStatus")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_status");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("processed_date");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("processing_status");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("received_date");

                    b.Property<string>("RequestPayload")
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("request_payload");

                    b.Property<string>("ShopId")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("shop_id");

                    b.Property<string>("SignatureStatus")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("signature_status");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("tracking_number");

                    b.HasKey("WebhookEventRecordId")
                        .HasName("PK_t_oms_webhook_event");

                    b.HasIndex("EventKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_t_oms_webhook_event_key");

                    b.HasIndex("Platform", "ProcessingStatus", "ReceivedDate")
                        .HasDatabaseName("IX_t_oms_webhook_event_processing");

                    b.HasIndex("Platform", "ShopId", "PlatformOrderId", "EventTime")
                        .HasDatabaseName("IX_t_oms_webhook_event_order");

                    b.ToTable("t_oms_webhook_event", "oms");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.WmsOutboundMaster", b =>
                {
                    b.Property<Guid>("OutboundOrderMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outbound_order_master_id");

                    b.Property<string>("CustomerOrderNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("customer_order_number");

                    b.Property<string>("OutboundOrderNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("outbound_order_number");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_id");

                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("platform");

                    b.Property<Guid>("WhMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wh_master_id");

                    b.HasKey("OutboundOrderMasterId");

                    b.ToTable("t_wms_outbound_master", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.WmsOutboundPackingDetail", b =>
                {
                    b.Property<Guid>("OutboundSortDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outbound_sort_detail_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_date");

                    b.Property<string>("ExpiryDate")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("expiry_date");

                    b.Property<string>("ItemDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("item_description");

                    b.Property<Guid>("ItemMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("item_master_id");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("item_number");

                    b.Property<Guid>("ItemUomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("item_uom_id");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("lot_number");

                    b.Property<DateTime?>("MfgDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("mfg_date");

                    b.Property<Guid>("OutboundSortMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outbound_sort_master_id");

                    b.Property<double>("QuantitySort")
                        .HasColumnType("float")
                        .HasColumnName("quantity_sort");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<string>("Uom")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("uom");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("update_date");

                    b.Property<Guid>("WhItemMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wh_item_master_id");

                    b.HasKey("OutboundSortDetailId");

                    b.ToTable("t_wms_outbound_packing_detail", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.WmsOutboundPackingMaster", b =>
                {
                    b.Property<Guid>("OutboundSortMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outbound_sort_master_id");

                    b.Property<int>("BoxNumber")
                        .HasColumnType("int")
                        .HasColumnName("box_number");

                    b.Property<string>("BoxSize")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("box_size");

                    b.Property<Guid?>("CarrierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("carrier_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_date");

                    b.Property<string>("IsCloseBox")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("is_close_box");

                    b.Property<Guid>("OutboundOrderMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outbound_order_master_id");

                    b.Property<string>("OutboundOrderNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("outbound_order_number");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<double?>("TotalWeight")
                        .HasColumnType("float")
                        .HasColumnName("total_weight");

                    b.Property<string>("TrackingNo")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("tracking_no");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("update_date");

                    b.Property<Guid>("WhMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wh_master_id");

                    b.HasKey("OutboundSortMasterId");

                    b.ToTable("t_wms_outbound_packing_master", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformOrderItem", b =>
                {
                    b.HasOne("OmsApi.Models.Persistence.PlatformOrder", "PlatformOrder")
                        .WithMany("Items")
                        .HasForeignKey("OrderRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_t_oms_order_item_order");

                    b.Navigation("PlatformOrder");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformPackage", b =>
                {
                    b.HasOne("OmsApi.Models.Persistence.PlatformOrder", "PlatformOrder")
                        .WithMany("Packages")
                        .HasForeignKey("OrderRecordId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_t_oms_platform_package_order");

                    b.Navigation("PlatformOrder");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformPackageItem", b =>
                {
                    b.HasOne("OmsApi.Models.Persistence.PlatformPackage", "PlatformPackage")
                        .WithMany("Items")
                        .HasForeignKey("PlatformPackageRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_t_oms_platform_package_item_package");

                    b.Navigation("PlatformPackage");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformSyncLogDetail", b =>
                {
                    b.HasOne("OmsApi.Models.Persistence.PlatformSyncLog", "SyncLog")
                        .WithMany("Details")
                        .HasForeignKey("SyncLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_t_oms_sync_log_detail_log");

                    b.Navigation("SyncLog");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformOrder", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Packages");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformPackage", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformSyncLog", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
