// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmsApi.Extensions;

#nullable disable

namespace OmsApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260923021947_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformCredential", b =>
                {
                    b.Property<long>("PlatformCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("platform_credential_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PlatformCredentialId"));

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("access_token_encrypted");

                    b.Property<DateTime>("AccessTokenExpiresDate")
                        .HasColumnType("datetime")
                        .HasColumnName("access_token_expires_date");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("create_date");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("YES")
                        .HasColumnName("is_active");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastRefreshDate")
                        .HasColumnType("datetime")
                        .HasColumnName("last_refresh_date");

                    b.Property<DateTime?>("LastUseDate")
                        .HasColumnType("datetime")
                        .HasColumnName("last_use_date");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("platform");

                    b.Property<string>("RefreshTokenEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("refresh_token_encrypted");

                    b.Property<DateTime?>("RefreshTokenExpiresDate")
                        .HasColumnType("datetime")
                        .HasColumnName("refresh_token_expires_date");

                    b.Property<string>("RequiresReauthorization")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("NO")
                        .HasColumnName("requires_reauthorization");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("shop_id");

                    b.Property<string>("ShopName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("shop_name");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date");

                    b.HasKey("PlatformCredentialId")
                        .HasName("PK_t_oms_platform_credential");

                    b.HasIndex("Platform", "ShopId")
                        .IsUnique()
                        .HasDatabaseName("UQ_t_oms_platform_credential_platform_shop");

                    b.ToTable("t_oms_platform_credential", "oms");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformDocument", b =>
                {
                    b.Property<long>("PlatformDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("platform_document_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PlatformDocumentId"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("create_date");

                    b.Property<string>("DocumentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("document_status");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileChecksum")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("file_checksum");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastPrintDate")
                        .HasColumnType("datetime")
                        .HasColumnName("last_print_date");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("platform");

                    b.Property<string>("PlatformOrderId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_order_id");

                    b.Property<string>("PlatformPackageId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_package_id");

                    b.Property<string>("PlatformRequestId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_request_id");

                    b.Property<int>("PrintCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("print_count");

                    b.Property<string>("PrintStorageKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("print_storage_key");

                    b.Property<string>("RawStorageKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("raw_storage_key");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("shop_id");

                    b.Property<string>("SourceContentType")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("source_content_type");

                    b.Property<DateTime?>("SourceExpiresDate")
                        .HasColumnType("datetime")
                        .HasColumnName("source_expires_date");

                    b.Property<string>("SourceFormat")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("source_format");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("tracking_number");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date");

                    b.HasKey("PlatformDocumentId")
                        .HasName("PK_t_oms_platform_document");

                    b.HasIndex("Platform", "ShopId", "PlatformOrderId", "PlatformPackageId", "DocumentType")
                        .IsUnique()
                        .HasDatabaseName("UQ_t_oms_platform_document_package")
                        .HasFilter("[platform_package_id] IS NOT NULL");

                    b.ToTable("t_oms_platform_document", "oms");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformPackage", b =>
                {
                    b.Property<long>("PlatformPackageRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("platform_package_record_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PlatformPackageRecordId"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<int>("BoxNumber")
                        .HasColumnType("int")
                        .HasColumnName("box_number");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("create_date");

                    b.Property<string>("CustomerOrderNumber")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("customer_order_number");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("datetime")
                        .HasColumnName("last_sync_date");

                    b.Property<Guid>("OutboundOrderMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outbound_order_master_id");

                    b.Property<Guid>("OutboundSortMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outbound_sort_master_id");

                    b.Property<string>("PackageStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("package_status");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("platform");

                    b.Property<string>("PlatformOrderId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_order_id");

                    b.Property<string>("PlatformPackageId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_package_id");

                    b.Property<string>("RequestId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("request_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<string>("ShippingProviderId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("shipping_provider_id");

                    b.Property<string>("ShippingProviderName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("shipping_provider_name");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("shop_id");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("sync_status");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("tracking_number");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date");

                    b.HasKey("PlatformPackageRecordId")
                        .HasName("PK_t_oms_platform_package");

                    b.HasIndex("SyncStatus", "LastSyncDate")
                        .HasDatabaseName("IX_t_oms_platform_package_sync");

                    b.HasIndex("Platform", "ShopId", "OutboundSortMasterId")
                        .IsUnique()
                        .HasDatabaseName("UQ_t_oms_platform_package_wms");

                    b.HasIndex("Platform", "ShopId", "PlatformPackageId")
                        .HasDatabaseName("IX_t_oms_platform_package_platform_id")
                        .HasFilter("[platform_package_id] IS NOT NULL");

                    b.HasIndex("Platform", "ShopId", "PlatformOrderId", "BoxNumber")
                        .HasDatabaseName("IX_t_oms_platform_package_order");

                    b.ToTable("t_oms_platform_package", "oms");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformPackageItem", b =>
                {
                    b.Property<long>("PlatformPackageItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("platform_package_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PlatformPackageItemId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("create_date");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("item_number");

                    b.Property<string>("PlatformItemId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_item_id");

                    b.Property<long>("PlatformPackageRecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("platform_package_record_id");

                    b.Property<string>("PlatformSkuId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("platform_sku_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date");

                    b.Property<Guid>("WmsItemMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wms_item_master_id");

                    b.HasKey("PlatformPackageItemId")
                        .HasName("PK_t_oms_platform_package_item");

                    b.HasIndex("PlatformPackageRecordId", "ItemNumber")
                        .HasDatabaseName("IX_t_oms_platform_package_item_package");

                    b.ToTable("t_oms_platform_package_item", "oms");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.WmsOutboundMaster", b =>
                {
                    b.Property<Guid>("OutboundOrderMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outbound_order_master_id");

                    b.Property<string>("CustomerOrderNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("customer_order_number");

                    b.Property<string>("OutboundOrderNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("outbound_order_number");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_id");

                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("platform");

                    b.Property<Guid>("WhMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wh_master_id");

                    b.HasKey("OutboundOrderMasterId");

                    b.ToTable("t_wms_outbound_master", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.WmsOutboundPackingDetail", b =>
                {
                    b.Property<Guid>("OutboundSortDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outbound_sort_detail_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_date");

                    b.Property<string>("ExpiryDate")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("expiry_date");

                    b.Property<string>("ItemDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("item_description");

                    b.Property<Guid>("ItemMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("item_master_id");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("item_number");

                    b.Property<Guid>("ItemUomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("item_uom_id");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("lot_number");

                    b.Property<DateTime?>("MfgDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("mfg_date");

                    b.Property<Guid>("OutboundSortMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outbound_sort_master_id");

                    b.Property<double>("QuantitySort")
                        .HasColumnType("float")
                        .HasColumnName("quantity_sort");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<string>("Uom")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("uom");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("update_date");

                    b.Property<Guid>("WhItemMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wh_item_master_id");

                    b.HasKey("OutboundSortDetailId");

                    b.ToTable("t_wms_outbound_packing_detail", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.WmsOutboundPackingMaster", b =>
                {
                    b.Property<Guid>("OutboundSortMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outbound_sort_master_id");

                    b.Property<int>("BoxNumber")
                        .HasColumnType("int")
                        .HasColumnName("box_number");

                    b.Property<string>("BoxSize")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("box_size");

                    b.Property<Guid?>("CarrierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("carrier_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_date");

                    b.Property<string>("IsCloseBox")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("is_close_box");

                    b.Property<Guid>("OutboundOrderMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outbound_order_master_id");

                    b.Property<string>("OutboundOrderNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("outbound_order_number");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<double?>("TotalWeight")
                        .HasColumnType("float")
                        .HasColumnName("total_weight");

                    b.Property<string>("TrackingNo")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("tracking_no");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("update_date");

                    b.Property<Guid>("WhMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wh_master_id");

                    b.HasKey("OutboundSortMasterId");

                    b.ToTable("t_wms_outbound_packing_master", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformPackageItem", b =>
                {
                    b.HasOne("OmsApi.Models.Persistence.PlatformPackage", "PlatformPackage")
                        .WithMany("Items")
                        .HasForeignKey("PlatformPackageRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_t_oms_platform_package_item_package");

                    b.Navigation("PlatformPackage");
                });

            modelBuilder.Entity("OmsApi.Models.Persistence.PlatformPackage", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
