import {
  Alert,
  Box,
  Button,
  Chip,
  IconButton,
  Paper,
  Typography,
  Tooltip,
  Collapse,
  Divider,
  useTheme,
} from "@mui/material";
import { Delete } from "@mui/icons-material";
import { useCallback, useMemo, useRef, useState, useEffect } from "react";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import ListAltOutlinedIcon from "@mui/icons-material/ListAltOutlined";
import FilterListOutlinedIcon from "@mui/icons-material/FilterListOutlined";
import AutoAwesomeOutlinedIcon from "@mui/icons-material/AutoAwesomeOutlined";
import RefreshOutlinedIcon from "@mui/icons-material/RefreshOutlined";
import DescriptionOutlinedIcon from "@mui/icons-material/DescriptionOutlined";
import CheckCircleOutlineIcon from "@mui/icons-material/CheckCircleOutline";
import BSAutoComplete from "../../components/BSAutoComplete";
import BSTextField from "../../components/BSTextField";
import BSDatepicker from "../../components/BSDatepicker";
import BSAlertSwal2 from "../../components/BSAlertSwal2";
import { BSDataGrid, BSDataGridClient } from "../../components/BSDataGrid";
import AxiosMaster from "../../utils/AxiosMaster";
import dayjs from "dayjs";
import { motion } from "framer-motion";
import ExpandLessIcon from "@mui/icons-material/ExpandLess";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import SecureStorage from "../../utils/SecureStorage";
import { useResource } from "../../hooks/useResource";
import CloseIcon from "@mui/icons-material/Close";
import SaveOutlinedIcon from "@mui/icons-material/SaveOutlined";
import { ButtonConfigs } from "../../utils/ButtonConfigs";

const COUNT_RESOURCE_GROUP = "v_inv_count_master";

const COUNT_LABEL_DEFS = {
  countPlanTypeRequired: [
    "CountPlanTypeRequired",
    "Count Plan Type is required",
  ],
  planDateRequired: ["PlanDateRequired", "Plan Date is required"],
  countingPlanCreated: ["CountingPlanCreated", "Counting plan created."],
  saveFailed: ["SaveFailed", "Save failed."],
  deleteStatusOpenOnly: [
    "DeleteStatusOpenOnly",
    "Can only delete records with status 'Open'.",
  ],
  deleteConfirmation: ["DeleteConfirmation", "Delete Confirmation"],
  deleteConfirm: ["Delete", "Delete"],
  cancel: ["Cancel", "Cancel"],
  deletedSuccessfully: ["DeletedSuccessfully", "Deleted successfully."],
  deleteFailed: ["DeleteFailed", "Delete failed."],
  countNumber: ["CountNumber", "Count Number"],
  description: ["Description", "Description"],
  countStatus: ["CountStatus", "Count Status"],
  createDate: ["CreateDate", "Create Date"],
  createBy: ["CreateBy", "Create By"],
  zone: ["Zone", "Zone"],
  location: ["Location", "Location"],
  itemNumber: ["ItemNumber", "Item Number"],
  itemDescription: ["ItemDescription", "Item Description"],
  lotNumber: ["LotNumber", "Lot Number"],
  expiryDate: ["ExpiryDate", "Expiry Date"],
  serialNumber: ["SerialNumber", "Serial Number"],
  quantityStock: ["QuantityStock", "Quantity Stock"],
  uom: ["UOM", "UOM"],
  viewCountingPlan: ["ViewCountingPlan", "View Counting Plan"],
  editCountingPlan: ["EditCountingPlan", "Edit Counting Plan"],
  createCountingPlan: ["CreateCountingPlan", "Create Counting Plan"],
  createdBy: ["CreatedBy", "Created by"],
  on: ["On", "on"],
  countPlanSubtitle: [
    "CountPlanSubtitle",
    "Plan an inventory cycle count or full count",
  ],
  countPlan: ["CountPlan", "Count Plan"],
  collapseCountPlan: ["CollapseCountPlan", "Collapse count plan"],
  expandCountPlan: ["ExpandCountPlan", "Expand count plan"],
  countId: ["CountId", "Count ID"],
  autoGeneratedOnSave: ["AutoGeneratedOnSave", "Auto-generated on save"],
  countType: ["CountType", "Count Type"],
  planDate: ["PlanDate", "Plan Date"],
  descriptionPlaceholder: [
    "DescriptionPlaceholder",
    "Counting plan description...",
  ],
  remark: ["Remark", "Remark"],
  remarkPlaceholder: ["RemarkPlaceholder", "Additional remark..."],
  updateBy: ["UpdateBy", "Update By"],
  updateDate: ["UpdateDate", "Update Date"],
  cycleCountCriteria: ["CycleCountCriteria", "Cycle Count Criteria"],
  cycleCriteriaInfo: [
    "CycleCriteriaInfo",
    "Specify any combination of criteria to filter inventory records. At least one criteria must be provided. Click Generate to populate the Count Plan Detail with matching items.",
  ],
  locationFrom: ["LocationFrom", "Location From"],
  locationTo: ["LocationTo", "Location To"],
  category: ["Category", "Category"],
  clear: ["Clear", "Clear"],
  generate: ["Generate", "Generate"],
  generating: ["Generating", "Generating..."],
  generateDetail: ["GenerateDetail", "Generate Detail"],
  countPlanDetail: ["CountPlanDetail", "Count Plan Detail"],
  cycleDetailRequired: [
    "CycleDetailRequired",
    "Cycle Count requires at least 1 detail row. Please click Generate Detail before saving.",
  ],
  cycleCriteriaPrompt: [
    "CycleCriteriaPrompt",
    "Set cycle criteria and click Generate Detail to build the grid.",
  ],
  selectCountTypePrompt: [
    "SelectCountTypePrompt",
    "Select Count Plan Type to display detail grid.",
  ],
  completeCount: ["CompleteCount", "Complete Count"],
  save: ["Save", "Save"],
  requiredFieldsText: [
    "RequiredFieldsText",
    "Required fields are marked with *",
  ],
  back: ["Back", "Back"],
};

const getStoredUserInfo = () => {
  const raw = SecureStorage.get("userInfo");
  let userInfo = raw;

  if (typeof raw === "string") {
    try {
      userInfo = JSON.parse(raw);
    } catch {
      userInfo = {};
    }
  }

  const firstName = userInfo?.FirstName || userInfo?.firstName || "";
  const lastName = userInfo?.LastName || userInfo?.lastName || "";
  const fullName = `${firstName} ${lastName}`.trim();

  return {
    raw: userInfo || {},
    userId:
      userInfo?.UserId ||
      userInfo?.userId ||
      userInfo?.user_id ||
      userInfo?.username ||
      "system",
    userName:
      fullName ||
      userInfo?.UserName ||
      userInfo?.username ||
      userInfo?.user_name ||
      userInfo?.Name ||
      "Current User",
    device: userInfo?.device || null,
  };
};

const initialForm = {
  count_master_id: "",
  count_number: "",
  count_type: "",
  count_status: "Open",
  count_plan_date: dayjs(),
  warehouse_id: "",
  warehouse: "",
  owner_id: "",
  owner_code: "",
  description: "",
  remark: "",
  create_by: "",
  create_date: null,
  update_by: "",
  update_date: null,
};

const ALL_CATEGORY_OPTION = {
  code: "",
  value: "All Categories",
  category_id: "",
  item_category: "All Categories",
};

const ALL_ITEM_OPTION = {
  code: "",
  value: "All Items",
  item_master_id: "",
  item_number: "All Items",
};

const initialCriteria = {
  location_from: "",
  location_to: "",
  category_id: "",
  item_category: ALL_CATEGORY_OPTION.value,
  item_master_id: "",
  item_number: ALL_ITEM_OPTION,
};

const getStatusLabel = (row) => {
  const closeRemark = String(row?.close_remark || "").toLowerCase();
  if (closeRemark.includes("cancel")) return "Cancelled";
  if (row?.close_date) return "Completed";
  if (row?.update_date) return "In Progress";
  return "Open";
};

const getStatusColor = (status) => {
  if (status === "Completed")
    return { text: "#00a86b", border: "#8fdac0", bg: "#e9f8f2" };
  if (status === "In Progress")
    return { text: "#f59e0b", border: "#f4cf8f", bg: "#fff5e5" };
  if (status === "Cancelled")
    return { text: "#6b7280", border: "#cfd4dc", bg: "#f3f4f6" };
  return { text: "#2f6fed", border: "#9dbcf7", bg: "#eaf1ff" };
};

const SectionHead = ({ icon, children, suffix }) => (
  <Box
    sx={{
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 1,
      mb: 1.5,
      color: "#3b56c5",
    }}
  >
    <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
      {icon}
      <Typography
        variant="h5"
        sx={{ color: "#3b56c5", fontWeight: 700, fontSize: 18 }}
      >
        {children}
      </Typography>
    </Box>
    {suffix}
  </Box>
);

const formatDateTime = (val) => {
  if (!val) return "-";
  const d = dayjs(val);
  return d.isValid() ? d.format("DD/MM/YYYY HH:mm") : "-";
};

const Count = (props) => {
  const { ACTION_BUTTON_THEMES } = ButtonConfigs();
  const theme = useTheme();
  const { getResourceByGroupAndName } = useResource();
  const [locale_id, setLocale_id] = useState(props.lang || "en");
  const gridRef = useRef(null);
  const detailGridRef = useRef(null);
  const [countPlanExpanded, setCountPlanExpanded] = useState(true);
  const [view, setView] = useState("list");
  const [isEdit, setIsEdit] = useState(false);
  const [isView, setIsView] = useState(false);
  const [form, setForm] = useState(initialForm);
  const [criteria, setCriteria] = useState(initialCriteria);
  const [generating, setGenerating] = useState(false);
  const [cycleGenerated, setCycleGenerated] = useState(false);
  // Keep previous criteria to detect changes
  const prevCriteriaRef = useRef(criteria);
  // Declare planType and isCycleCount ONCE, above all hooks that use them
  const planType = form.count_type;
  const isCycleCount = planType === "Cycle Count";
  const [errors, setErrors] = useState({});
  const [cycleLines, setCycleLines] = useState([]);

  useEffect(() => {
    setLocale_id(props.lang || "en");
  }, [props.lang]);

  const labels = useMemo(
    () =>
      Object.fromEntries(
        Object.entries(COUNT_LABEL_DEFS).map(
          ([labelKey, [resourceName, fallback]]) => [
            labelKey,
            getResourceByGroupAndName(
              COUNT_RESOURCE_GROUP,
              resourceName,
              locale_id,
            )?.resource_value || fallback,
          ],
        ),
      ),
    [getResourceByGroupAndName, locale_id],
  );

  const normalizeStatus = (status) =>
    String(status || "")
      .trim()
      .toUpperCase();

  const currentUserInfo = useMemo(() => getStoredUserInfo(), []);
  const currentUserId = currentUserInfo.userId;

  const handleOpenAdd = () => {
    setForm(initialForm);
    setCriteria(initialCriteria);
    setCycleGenerated(false);
    setErrors({});
    setIsEdit(false);
    setIsView(false);
    setView("form");
  };

  const openExistingCount = (row, mode = "edit") => {
    setForm({
      count_master_id: row.count_master_id ?? "",
      count_number: row.count_number ?? "",
      count_type: row.count_type ?? "",
      count_status: row.count_status ?? getStatusLabel(row),
      count_plan_date: row.count_plan_date
        ? new Date(row.count_plan_date)
        : null,
      warehouse_id: row.warehouse_id ?? "",
      warehouse: row.warehouse ?? "",
      owner_id: row.owner_id ?? "",
      owner_code: row.owner_code ?? "",
      description: row.description ?? "",
      remark: row.remark ?? "",
      create_by: row.create_by ?? "",
      create_date: row.create_date ? new Date(row.create_date) : null,
      update_by: row.update_by ?? "",
      update_date: row.update_date ? new Date(row.update_date) : null,
    });
    setCriteria(initialCriteria);
    setCycleGenerated(false);
    setErrors({});
    setIsEdit(mode === "edit");
    setIsView(mode === "view");
    setView("form");
  };

  const handleOpenEdit = (row) => {
    openExistingCount(row, "edit");
  };

  const handleOpenView = (row) => {
    openExistingCount(row, "view");
  };

  const handleBack = () => {
    setView("list");
    setIsEdit(false);
    setIsView(false);
  };

  const handleClearCriteria = () => {
    setCriteria(initialCriteria);
    setCycleGenerated(false);
  };

  // For Cycle Count, just set cycleGenerated to true and let grid use criteria for where
  const handleGenerateDetail = useCallback(async () => {
    setGenerating(true);
    try {
      const payload = {
        location_from: criteria.location_from.location || "",
        location_to: criteria.location_to.location || "",
        category: criteria.category_id.item_category || "",
        item_number:
          criteria.item_number?.item_number === "All Items"
            ? ""
            : criteria.item_number?.item_number || "",
      };

      const response = await AxiosMaster.post("/count/cycleCountData", payload);

      const result = response.data.data;
      if (!result.success) {
        BSAlertSwal2.show("error", result.message);
        setCycleLines([]);
        return;
      }

      if (!result.data || result.data.length === 0) {
        BSAlertSwal2.show("warning", "No Data Found");
        setCycleLines([]);
        return;
      }

      setCycleLines((prev) => {
        const newItems = result.data.filter(
          (newItem) =>
            !prev.some(
              (oldItem) =>
                oldItem.inventory_id_serial === newItem.inventory_id_serial &&
                oldItem.inventory_id === newItem.inventory_id,
            ),
        );

        return [...prev, ...newItems];
      });

      setCycleGenerated(true);
      prevCriteriaRef.current = criteria;
    } catch (err) {
      BSAlertSwal2.show("error", err);
      setCycleLines([]);
    } finally {
      setGenerating(false);
    }
  }, [criteria]);

  // Whenever criteria changes, reset cycleGenerated to false (only for Cycle Count, new mode)
  useEffect(() => {
    if (
      !isEdit &&
      !isView &&
      planType === "Cycle Count" &&
      cycleGenerated &&
      JSON.stringify(criteria) !== JSON.stringify(prevCriteriaRef.current)
    ) {
      setCycleGenerated(false);
      setCycleLines([]);
    }
  }, [criteria, isEdit, isView, planType, cycleGenerated]);

  const validate = () => {
    const e = {};
    if (!form.count_type) e.count_type = labels.countPlanTypeRequired;
    if (!form.count_plan_date) e.count_plan_date = labels.planDateRequired;
    // if (!form.warehouse_id) e.warehouse_id = "Warehouse is required";
    // if (!form.owner_id) e.owner_id = "Owner is required";
    setErrors(e);
    return Object.keys(e).length === 0;
  };

  const handleSave = async () => {
    if (!validate()) {
      // console.log("validate failed", errors, form);
      return;
    }

    // const device = userInfo?.device || userInfo?.Device || null;
    const language = locale_id || "en";
    const isNewRecord = !form.count_master_id;

    // Prepare details
    let details = [];
    if (form.count_type === "Cycle Count") {
      // Read all rows from Count Plan Detail Grid, fallback to state.
      details = cycleLines;

      if (!Array.isArray(details) || details.length === 0) {
        BSAlertSwal2.show("warning", labels.cycleDetailRequired);
        return;
      }
    }

    // Map details to API format if needed
    details = Array.isArray(details)
      ? details.map((row) => ({
          count_detail_id: row.count_detail_id || 0,
          count_master_id: form.count_master_id || 0,
          location_id: row.location_id || 0,
          location: row.location || "",
          item_master_id: row.item_master_id || 0,
          item_number: row.item_number || "",
          item_description:
            row.item_description || row.description || row.item_desc || "",
          quantity_stock:
            row.quantity_stock || row.quantity || row.book_qty || 0,
          item_uom_id: row.item_uom_id || 0,
          uom: row.uom || "",
          inv_status: row.inv_status || "",
          lot_number: row.lot_number || row.lot || "",
          expiry_date: row.expiry_date
            ? dayjs(row.expiry_date).format("YYYY-MM-DD")
            : null,
          serial_number: row.serial_number || row.serial_no || "",
          receive_date: row.receive_date
            ? dayjs(row.receive_date).format("YYYY-MM-DD")
            : null,
        }))
      : [];

    const payload = {
      count_master_id: form.count_master_id || 0,
      warehouse_id: form.warehouse_id || 0,
      warehouse: form.warehouse || "",
      owner_id: form.owner_id || 0,
      owner_code: form.owner_code || "",
      count_number: form.count_number || "",
      count_status: form.count_status || "",
      count_type: form.count_type || "",
      description: form.description || "",
      user_id: String(currentUserId),
      //device: device,
      language: language,
      details: form.count_type === "Cycle Count" ? details : [],
      count_plan_date: form.count_plan_date
        ? dayjs(form.count_plan_date).format("YYYY-MM-DD")
        : "",
      remark: form.remark || "",
    };

    try {
      const response = await AxiosMaster.post("/count/insert", payload);
      const responseData = response?.data?.data ?? response?.data ?? {};

      if (responseData?.success === false) {
        BSAlertSwal2.show("error", responseData?.message || labels.saveFailed);
        return;
      }

      const savedCountMasterId =
        responseData?.count_master_id ?? form.count_master_id;
      const savedCountNumber = responseData?.count_number ?? form.count_number;

      if (savedCountMasterId || savedCountNumber) {
        setForm((prev) => ({
          ...prev,
          count_master_id: savedCountMasterId || prev.count_master_id,
          count_number: savedCountNumber || prev.count_number,
          ...(isNewRecord
            ? {
                create_by: prev.create_by || currentUserInfo.userName,
                create_date: prev.create_date || new Date(),
              }
            : {}),
        }));
      }

      BSAlertSwal2.show(
        "success",
        responseData?.message || labels.countingPlanCreated,
        { timer: 2000 },
      );
      setView("form");
      setIsEdit(false);
      setIsView(true);
      gridRef.current?.refreshData();
    } catch (err) {
      console.log("save error", err);
      BSAlertSwal2.show("error", err?.message || labels.saveFailed);
    }
  };

  const resolveDeleteTarget = (input) => {
    if (input == null) {
      return form;
    }

    if (typeof input !== "object") {
      return {
        ...form,
        count_master_id: input,
      };
    }

    if (
      !("target" in input) &&
      !("currentTarget" in input) &&
      (input.count_master_id !== undefined ||
        input.count_number !== undefined ||
        input.count_status !== undefined)
    ) {
      return input;
    }

    return form;
  };

  const handleDelete = async (rowOrEvent) => {
    const target = resolveDeleteTarget(rowOrEvent);

    // ลบได้เฉพาะสถานะ Open เท่านั้น
    if (
      target.count_status &&
      String(target.count_status).toUpperCase() !== "OPEN"
    ) {
      BSAlertSwal2.show("warning", labels.deleteStatusOpenOnly);
      return;
    }

    const confirmed = await BSAlertSwal2.confirm(
      `Confirm delete count plan ${target.count_number}?`,
      {
        title: labels.deleteConfirmation,
        confirmButtonText: labels.deleteConfirm,
        cancelButtonText: labels.cancel,
      },
    );
    if (!confirmed) return;
    const language = locale_id || "en";

    const payload = {
      count_master_id: target.count_master_id || 0,
      user_id: String(currentUserId),
      //device: device,
      language: language,
    };

    try {
      await AxiosMaster.post("/count/delete", payload);
      BSAlertSwal2.show("success", labels.deletedSuccessfully, { timer: 2000 });
      setView("list");
      setIsEdit(false);
      setIsView(false);
      gridRef.current?.refreshData();
    } catch (err) {
      BSAlertSwal2.show("error", err?.message || labels.deleteFailed);
    }
  };

  const handleDeleteRow = async (row) => {
    setCycleLines((prev) =>
      prev.filter(
        (item) =>
          !(
            item.inventory_id === row.inventory_id &&
            item.inventory_id_serial === row.inventory_id_serial
          ),
      ),
    );
  };

  const columnDefs = useMemo(
    () => [
      { field: "count_master_id", hide: true },
      {
        field: "count_number",
        headerName: labels.countNumber,
        width: 160,
        renderCell: (params) => (
          <Typography
            component="span"
            sx={{ color: "#3b56c5", fontWeight: 700 }}
          >
            {params.value}
          </Typography>
        ),
      },
      { field: "warehouse", hide: true },
      { field: "owner_code", hide: true },
      { field: "count_plan_date", hide: true },
      { field: "remark", hide: true },
      {
        field: "description",
        headerName: labels.description,
        // flex: 1,
        width: 280,
      },
      {
        field: "count_status",
        headerName: labels.countStatus,
        width: 120,
        sortable: false,
        filterable: false,
        renderCell: (params) => {
          const status = getStatusLabel(params.row);
          const palette = getStatusColor(status);
          return (
            <motion.div
              whileHover={{ scale: 1.08 }}
              transition={{
                type: "spring",
                stiffness: 300,
                damping: 20,
              }}
            >
              <Chip
                size="small"
                label={status}
                sx={{
                  color: palette.text,
                  backgroundColor: "transparent",
                  border: "none",
                  fontWeight: 700,
                  minWidth: 96,
                }}
              />
            </motion.div>
          );
        },
      },
      {
        field: "create_date",
        type: "datetime",
      },
      { field: "create_by", headerName: labels.createBy },
      { field: "close_by", hide: false },
      { field: "close_date", hide: false },
      { field: "close_remark", hide: false },
      { field: "warehouse_id", hide: true },
      { field: "owner_id", hide: true },
      { field: "update_by" },
      { field: "update_date", type: "datetime" },
    ],
    [labels],
  );

  const countMasterWhere = form.count_master_id
    ? `count_master_id = '${String(form.count_master_id).replace(/'/g, "''")}'`
    : "1=0";

  const detailColumnDefs = useMemo(
    () => [
      { field: "zone", headerName: labels.zone },
      { field: "location", headerName: labels.location },
      {
        field: "item_number",
        headerName: labels.itemNumber,
        width: 170,
        renderCell: (params) => (
          <Typography component="span" sx={{ fontWeight: 700 }}>
            {params.value}
          </Typography>
        ),
      },
      {
        field: "item_description",
        headerName: labels.itemDescription,
        width: 280,
      },
      { field: "lot_number", headerName: labels.lotNumber },
      { field: "expiry_date", headerName: labels.expiryDate },
      { field: "serial_number", headerName: labels.serialNumber },
      {
        field: "quantity",
        headerName: labels.quantityStock,
        type: "number",
      },
      { field: "uom", headerName: labels.uom },
      { field: "receive_date", hide: true },
      { field: "item_master_id", hide: true },
      { field: "item_uom_id", hide: true },
      { field: "location_id", hide: true },
      { field: "inv_status", hide: true },
    ],
    [labels],
  );

  // Show grid only in 'new' mode (not edit/view)
  // Physical Count: always show
  // Cycle Count: show only after pressing Generate Detail
  const shouldShowClientDetailGrid =
    !isEdit &&
    !isView &&
    (planType === "Physical Count" || (isCycleCount && cycleLines.length > 0));
  const shouldShowServerDetailGrid = isView && Boolean(form.count_master_id);

  if (view === "list") {
    return (
      <>
        <Paper
          sx={{
            p: 2,
            // mb: 3,
            width: "100%",
            maxWidth: "100%",
            height: "100%",
            display: "flex",
            flexDirection: "column",
          }}
        >
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
          >
            <BSDataGrid
              ref={gridRef}
              bsLocale={locale_id}
              bsAutoPermission={false}
              bsPreObj="inv"
              bsObj="t_inv_count_master"
              bsObjBy="create_date desc"
              bsCols="count_status,count_master_id,warehouse_id,warehouse,owner_id,owner_code,count_number,count_type,description,close_by,close_date,close_remark,create_by,create_date,update_by,update_date,count_plan_date,remark"
              bsKeyId="count_master_id"
              bsShowRowNumber={true}
              bsShowDescColumn={false}
              bsRowConfig={(row) => ({
                showDelete: normalizeStatus(row?.count_status) === "OPEN",
              })}
              bsVisibleView={true}
              bsVisibleEdit={false}
              bsVisibleDelete={true}
              bsAllowDelete={true}
              bsBulkMode={{ enable: false }}
              bsColumnDefs={columnDefs}
              onAdd={handleOpenAdd}
              onEdit={handleOpenEdit}
              onView={handleOpenView}
              onDelete={handleDelete}
              bsComboBox={[
                {
                  Column: "count_type",
                  Display: "display_member",
                  Value: "value_member",
                  Default: "--- Select Count Type ---",
                  PreObj: "sec",
                  Obj: "t_com_combobox_item",
                  ObjWh: "group_name= 'count_type' AND is_active=1",
                  ObjBy: "display_sequence asc",
                },
              ]}
            />
          </motion.div>
        </Paper>
      </>
    );
  }

  return (
    <Box
      sx={{
        p: 2.5,
        pb: 3,
        display: "flex",
        flexDirection: "column",
        minHeight: "100vh",
      }}
    >
      <Box
        sx={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          mb: 2.25,
        }}
      >
        <Box sx={{ display: "flex", alignItems: "center", gap: 1.5 }}>
          <motion.div
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
            transition={{ type: "spring", stiffness: 300, damping: 20 }}
          >
            <IconButton
              size="small"
              onClick={handleBack}
              sx={{ border: "1px solid", borderColor: "divider" }}
            >
              <ArrowBackIcon />
            </IconButton>
          </motion.div>
          <Box>
            <Box sx={{ display: "flex", alignItems: "center", gap: 1.25 }}>
              <Typography variant="h4" fontWeight={700}>
                {isView
                  ? labels.viewCountingPlan
                  : isEdit
                    ? labels.editCountingPlan
                    : labels.createCountingPlan}
              </Typography>
              {/* {(isEdit || isView) && (
                <Chip
                  size="small"
                  label={form.count_status || "Open"}
                  sx={{
                    ...(String(form.count_status || "Open").toUpperCase() ===
                    "OPEN"
                      ? {
                          bgcolor: "#95ffa9",
                          color: "#1b8500",
                          border: "1px solid #1b8500",
                        }
                      : {
                          bgcolor: "#fff4e5",
                          color: "#f59e0b",
                          border: "1px solid #f4cf8f",
                        }),
                    fontWeight: 700,
                  }}
                />
              )} */}
            </Box>
            <Typography color="text.secondary" fontSize="0.95rem">
              {isEdit
                ? `${form.count_number || "-"} · ${labels.createdBy} ${form.create_by || "-"} ${labels.on} ${formatDateTime(form.create_date)}`
                : labels.countPlanSubtitle}
            </Typography>
          </Box>
        </Box>
        {/* {(isEdit || isView) && (
          <Box sx={{ display: "flex", gap: 1.5 }}>
            <motion.div
              whileHover={{ scale: 1.03 }}
              whileTap={{ scale: 0.97 }}
              transition={{ type: "spring", stiffness: 300, damping: 22 }}
            >
              <Button
                variant="outlined"
                startIcon={<PrintOutlinedIcon />}
                onClick={handlePrint}
              >
                Print Count Sheet
              </Button>
            </motion.div>
            <motion.div
              whileHover={{ scale: 1.03 }}
              whileTap={{ scale: 0.97 }}
              transition={{ type: "spring", stiffness: 300, damping: 22 }}
            >
              <Button
                variant="outlined"
                startIcon={<HistoryOutlinedIcon />}
                onClick={handleHistory}
              >
                History
              </Button>
            </motion.div>
          </Box>
        )} */}
      </Box>

      <Paper
        sx={{
          borderRadius: 2,
          p: countPlanExpanded ? 2.5 : 1.25,
          mb: 1.5,
        }}
      >
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            gap: 1,
            mb: countPlanExpanded ? 1.5 : 0,
          }}
        >
          <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
            <DescriptionOutlinedIcon sx={{ color: "#3b56c5" }} />
            <Typography
              variant="h5"
              sx={{
                color: "#3b56c5",
                fontWeight: 700,
                fontSize: countPlanExpanded ? 18 : 16,
                lineHeight: 1.2,
              }}
            >
              {labels.countPlan}
            </Typography>
          </Box>

          <Box>
            <Tooltip
              title={
                countPlanExpanded
                  ? labels.collapseCountPlan
                  : labels.expandCountPlan
              }
              placement="bottom"
            >
              <IconButton
                size="small"
                onClick={() => setCountPlanExpanded((p) => !p)}
                aria-expanded={countPlanExpanded}
                sx={{
                  color: "#3b56c5",
                  borderRadius: 1,
                  boxShadow: countPlanExpanded
                    ? "0 1px 6px rgba(59,86,197,0.12)"
                    : undefined,
                  border: "1px solid",
                  borderColor: countPlanExpanded
                    ? "rgba(59,86,197,0.12)"
                    : "transparent",
                }}
              >
                {countPlanExpanded ? <ExpandLessIcon /> : <ExpandMoreIcon />}
              </IconButton>
            </Tooltip>
          </Box>
        </Box>

        <Collapse in={countPlanExpanded} unmountOnExit>
          <Divider sx={{ mb: 2.25 }} />

          <Box
            sx={{
              display: "grid",
              gridTemplateColumns: {
                xs: "1fr",
                md: "repeat(2, minmax(0, 1fr))",
                xl: "repeat(4, minmax(0, 1fr))",
              },
              gap: 1.75,
            }}
          >
            <BSTextField
              label={labels.countId}
              value={form.count_number || labels.autoGeneratedOnSave}
              disblsed
              InputLabelProps={{ shrink: true }}
              sx={{
                "& .MuiInputBase-input.Mui-disabled": {
                  WebkitTextFillColor: "rgba(0,0,0,0.38)",
                },
              }}
              fullWidth
            />

            <BSAutoComplete
              readOnly={isEdit || isView}
              bsTitle={labels.countType}
              bsPreObj="sec"
              bsObj="t_com_combobox_item"
              bsObjBy="display_sequence asc"
              bsObjWh="is_active=1 AND group_name='count_type' "
              bsCacheKey="count_type"
              bsValue={form.count_type}
              bsOnChange={(selected) => {
                setForm((p) => ({
                  ...p,
                  count_type: selected?.code ?? "",
                }));
                if (!isEdit) {
                  setCycleGenerated(false);
                  setCycleLines([]);
                  setCriteria(initialCriteria);
                }
                if (errors.count_type)
                  setErrors((p) => ({ ...p, count_type: "" }));
              }}
              error={!!errors.count_type}
              helperText={errors.count_type}
              required
              fullWidth
              bsColumes={[
                {
                  field: "value_member",
                  display: false,
                  filter: false,
                  key: true,
                },
                {
                  field: "display_member",
                  display: true,
                  filter: true,
                  key: false,
                },
              ]}
            />

            <BSTextField
              label={labels.countStatus}
              value={form.count_status}
              disblsed
              fullWidth
              InputLabelProps={{ shrink: true }}
              sx={{
                "& .MuiInputBase-input.Mui-disabled": {
                  WebkitTextFillColor: "rgba(0,0,0,0.6)",
                },
              }}
            />

            <BSDatepicker
              label={`${labels.planDate}`}
              value={form.count_plan_date ? dayjs(form.count_plan_date) : null}
              onChange={(val) =>
                setForm((p) => ({
                  ...p,
                  count_plan_date: val ? val.toDate() : null,
                }))
              }
              isDateOnly
              format="DD/MM/YYYY"
              required
              fullWidth
              error={!!errors.count_plan_date}
              helperText={errors.count_plan_date}
              readOnly={isView}
            />

            <Box
              sx={{ gridColumn: { xs: "1 / -1", md: "1 / 3", xl: "1 / 3" } }}
            >
              <BSTextField
                label={labels.description}
                placeholder={labels.descriptionPlaceholder}
                value={form.description}
                onChange={(val) => setForm((p) => ({ ...p, description: val }))}
                maxLength={255}
                fullWidth
                multiline
                minRows={3}
              />
            </Box>

            <Box
              sx={{ gridColumn: { xs: "1 / -1", md: "3 / 5", xl: "3 / 5" } }}
            >
              <BSTextField
                label={labels.remark}
                placeholder={labels.remarkPlaceholder}
                maxLength={255}
                value={form.remark}
                onChange={(val) => setForm((p) => ({ ...p, remark: val }))}
                size="small"
                multiline
                minRows={3}
                fullWidth
              />
            </Box>
          </Box>

          {(isEdit || isView) && (
            <Box
              sx={{
                mt: 2.5,
                p: 2,
                border: "1px solid",
                borderColor: "divider",
                borderRadius: 1.5,
                bgcolor: "grey.50",
                display: "grid",
                gridTemplateColumns: {
                  xs: "1fr",
                  md: "repeat(2, minmax(0, 1fr))",
                  xl: "repeat(4, minmax(160px, 1fr))",
                },
                gap: 1.75,
              }}
            >
              <Box>
                <Typography variant="caption" color="text.secondary">
                  {labels.createBy}
                </Typography>
                <Typography fontWeight={600}>
                  {form.create_by || "-"}
                </Typography>
              </Box>
              <Box>
                <Typography variant="caption" color="text.secondary">
                  {labels.createDate}
                </Typography>
                <Typography fontWeight={600}>
                  {formatDateTime(form.create_date)}
                </Typography>
              </Box>
              <Box>
                <Typography variant="caption" color="text.secondary">
                  {labels.updateBy}
                </Typography>
                <Typography fontWeight={600}>
                  {form.update_by || "-"}
                </Typography>
              </Box>
              <Box>
                <Typography variant="caption" color="text.secondary">
                  {labels.updateDate}
                </Typography>
                <Typography fontWeight={600}>
                  {formatDateTime(form.update_date)}
                </Typography>
              </Box>
            </Box>
          )}
        </Collapse>
      </Paper>

      {isCycleCount && !isView && (
        <Paper
          sx={{
            p: 2.5,
            mb: 2.5,
            borderRadius: 2,
            border: "1px solid",
            borderColor: "divider",
          }}
        >
          <SectionHead icon={<FilterListOutlinedIcon sx={{ fontSize: 18 }} />}>
            {labels.cycleCountCriteria}
          </SectionHead>
          <Divider sx={{ mb: 2.25 }} />
          <Alert severity="info" sx={{ mb: 2.5, fontSize: "0.82rem" }}>
            {labels.cycleCriteriaInfo}
          </Alert>
          <Box
            sx={{
              display: "grid",
              gridTemplateColumns: {
                xs: "1fr",
                md: "repeat(2, minmax(0, 1fr))",
                xl: "repeat(4, minmax(0, 1fr))",
              },
              gap: 1.75,
            }}
          >
            <Box>
              <BSAutoComplete
                bsTitle={labels.locationFrom}
                bsPreObj="inv"
                bsObj="t_inv_location"
                bsObjBy="location asc"
                bsObjWh="is_active=1 " //AND loc_type=N'PICK'
                bsColumes={[
                  { field: "location_id", key: true },
                  { field: "location", display: true },
                ]}
                bsValue={criteria.location_from}
                bsOnChange={(selected) =>
                  setCriteria((p) => ({
                    ...p,
                    location_from: selected ?? "",
                  }))
                }
              />
            </Box>
            <Box>
              <BSAutoComplete
                bsTitle={labels.locationTo}
                bsPreObj="inv"
                bsObj="t_inv_location"
                bsObjWh="is_active=1 " //AND loc_type=N'PICK'
                bsObjBy="location asc"
                bsColumes={[
                  { field: "location_id", key: true },
                  { field: "location", display: true },
                ]}
                bsValue={criteria.location_to}
                bsOnChange={(selected) =>
                  setCriteria((p) => ({
                    ...p,
                    location_to: selected ?? "",
                  }))
                }
              />
            </Box>
            <Box>
              <BSAutoComplete
                bsTitle={labels.category}
                bsPreObj="inv"
                bsObj="t_inv_category"
                bsObjBy="item_category asc"
                bsObjWh="is_active=1"
                bsColumes={[
                  { field: "category_id", key: true },
                  { field: "item_category", display: true },
                ]}
                bsValue={
                  criteria.category_id
                    ? criteria.category_id
                    : ALL_CATEGORY_OPTION
                }
                bsOnChange={(selected) =>
                  setCriteria((p) => ({
                    ...p,
                    category_id: selected || "",
                    item_category:
                      selected?.value ||
                      selected?.item_category ||
                      ALL_CATEGORY_OPTION.value,
                  }))
                }
                bsLoadOnOpen
              />
            </Box>
            <Box>
              <BSAutoComplete
                bsTitle={labels.itemNumber}
                bsPreObj="inv"
                bsObj="t_inv_item"
                bsObjWh="is_active=1"
                bsObjBy="item_number asc"
                bsColumes={[
                  { field: "item_master_id", key: true },
                  { field: "item_number", display: true },
                  { field: "description", display: true },
                ]}
                bsValue={criteria.item_number}
                bsOnChange={(selected) =>
                  setCriteria((p) => ({
                    ...p,
                    item_number: selected || ALL_ITEM_OPTION,
                    item_desc: selected?.value ?? "",
                  }))
                }
                bsLoadOnOpen
              />
            </Box>
          </Box>
          <Box
            sx={{
              display: "flex",
              justifyContent: "flex-end",
              gap: 1.5,
              mt: 2,
            }}
          >
            <motion.div
              whileHover={{ scale: 1.03 }}
              whileTap={{ scale: 0.97 }}
              transition={{ type: "spring", stiffness: 300, damping: 22 }}
            >
              <Button
                size="small"
                variant="outlined"
                startIcon={<RefreshOutlinedIcon />}
                onClick={handleClearCriteria}
                sx={{
                  ...ACTION_BUTTON_THEMES.clear,
                  borderColor: (theme) =>
                    theme.palette.mode === "dark"
                      ? "rgba(255, 255, 255, 0.15)"
                      : "rgba(0, 0, 0, 0.15)",
                  color: "text.primary",
                  textTransform: "none",
                  "&:hover": {
                    backgroundColor: "action.hover",
                    borderColor: (theme) =>
                      theme.palette.mode === "dark"
                        ? "rgba(255, 255, 255, 0.3)"
                        : "rgba(0, 0, 0, 0.25)",
                  },
                }}
              >
                {labels.clear}
              </Button>
            </motion.div>
            <motion.div
              whileHover={!generating ? { scale: 1.03 } : {}}
              whileTap={!generating ? { scale: 0.97 } : {}}
              transition={{ type: "spring", stiffness: 300, damping: 22 }}
            >
              <Button
                size="small"
                variant="contained"
                startIcon={<AutoAwesomeOutlinedIcon />}
                onClick={handleGenerateDetail}
                disabled={generating}
                sx={ACTION_BUTTON_THEMES.primary}
              >
                {generating ? labels.generating : labels.generateDetail}
              </Button>
            </motion.div>
          </Box>
        </Paper>
      )}

      <Paper sx={{ borderRadius: 2, p: 2.5, mb: 2.5 }}>
        <SectionHead icon={<ListAltOutlinedIcon sx={{ fontSize: 18 }} />}>
          {labels.countPlanDetail}
        </SectionHead>
        <Divider sx={{ mb: 2.25 }} />
        {shouldShowServerDetailGrid && (
          <Box
            sx={{
              border: "1px solid",
              borderColor: "divider",
              borderRadius: 1,
              overflow: "hidden",
              bgcolor: "background.paper",
            }}
          >
            <BSDataGrid
              key={`count-detail-${form.count_master_id || "empty"}`}
              bsLocale={locale_id}
              bsPreObj="inv"
              bsObj="v_inv_count_plan_detail"
              bsCols="zone,location,item_number,item_description,lot_number,expiry_date,serial_number,quantity_stock,uom,create_by,create_date"
              bsObjBy="create_date desc"
              bsShowDescColumn={true}
              bsKeyId="count_detail_id"
              showAdd={false}
              bsVisibleView={false}
              bsVisibleEdit={false}
              bsVisibleDelete={false}
              bsVisibleAdd={false}
              bsObjWh={countMasterWhere}
              bsColumnDefs={detailColumnDefs}
            />
          </Box>
        )}

        {shouldShowClientDetailGrid ? (
          planType === "Physical Count" ? (
            <Box
              sx={{
                border: "1px solid",
                borderColor: "divider",
                borderRadius: 1,
                overflow: "hidden",
                bgcolor: "background.paper",
              }}
            >
              <BSDataGrid
                ref={detailGridRef}
                bsLocale={locale_id}
                bsPreObj="inv"
                bsObj="v_inv_count_get_inventory"
                bsCols="zone,location,location_id,item_master_id,item_number,item_description,lot_number,expiry_date,serial_number,quantity,item_uom_id,uom,receive_date,inv_status"
                bsObjBy="zone,location,item_number asc"
                bsShowDescColumn={true}
                bsKeyId="inventory_id"
                showAdd={false}
                bsVisibleView={false}
                bsVisibleEdit={false}
                bsVisibleDelete={false}
                bsVisibleAdd={false}
                bsColumnDefs={detailColumnDefs}
                bsObjWh={"1=1"}
                // planType === "Cycle Count"
                //   ? (() => {
                //       const whs = [
                //         criteria.location_from &&
                //           `location_id >= '${criteria.location_from}'`,
                //         criteria.location_to &&
                //           `location_id <= '${criteria.location_to}'`,
                //         criteria.category_id &&
                //           `category_id = '${criteria.category_id}'`,
                //         criteria.item_number.item_master_id &&
                //           `item_master_id = '${criteria.item_number.item_master_id}'`,
                //       ].filter(Boolean);
                //       return whs.join(" AND ");
                //     })()
                //   : undefined
                //}
                // onDataBind={(data) => setDetailRows(data)}
              />
            </Box>
          ) : (
            <Box
              sx={{
                border: "1px solid",
                borderColor: "divider",
                borderRadius: 1,
                overflow: "hidden",
                bgcolor: "background.paper",
              }}
            >
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: 0.1 }}
              >
                <BSDataGridClient
                  data={cycleLines}
                  //bsCols="zone,location,location_id,item_master_id,item_number,item_description,lot_number,expiry_date,serial_number,quantity,item_uom_id,uom,receive_date,inv_status"
                  bsObjBy="zone,location,item_number asc"
                  bsLocale={locale_id}
                  bsShowRowNumber={true}
                  showToolbar={false}
                  pagination={false}
                  hideFooter
                  disableColumnMenu
                  disableColumnFilter
                  // disableColumnSelector
                  // disableDensitySelector
                  //bsShowCheckbox={true}
                  columnVisibilityModel={{
                    location_id: false,
                    item_master_id: false,
                    item_uom_id: false,
                    inv_status: false,
                    receive_date: false,
                  }}
                  columns={[
                    {
                      field: "action",
                      headerName: " ",
                      width: 60,
                      sortable: false,
                      filterable: false,
                      renderCell: (params) => (
                        <IconButton
                          size="small"
                          onClick={(e) => {
                            e.stopPropagation();

                            handleDeleteRow(params.row);
                          }}
                        >
                          <Delete fontSize="small" />
                        </IconButton>
                      ),
                    },
                    { field: "zone", headerName: labels.zone },
                    { field: "location", headerName: labels.location },
                    { field: "location_id" },
                    {
                      field: "item_master_id",
                    },
                    { field: "item_number", headerName: labels.itemNumber },
                    {
                      field: "item_description",
                      headerName: labels.itemDescription,
                    },
                    { field: "lot_number", headerName: labels.lotNumber },
                    {
                      field: "expiry_date",
                      headerName: labels.expiryDate,
                      type: "date",
                    },
                    {
                      field: "serial_number",
                      headerName: labels.serialNumber,
                    },
                    {
                      field: "quantity",
                      headerName: labels.quantity,
                      type: "number",
                    },
                    { field: "item_uom_id" },
                    { field: "uom", headerName: labels.uom },
                    {
                      field: "receive_date",
                      headerName: labels.receiveDate,
                      type: "date",
                    },
                    { field: "inv_status", headerName: labels.invStatus },
                  ]}
                />
              </motion.div>
            </Box>
          )
        ) : !shouldShowServerDetailGrid ? (
          <Alert severity="info" sx={{ fontSize: "0.82rem" }}>
            {planType === "Cycle Count"
              ? labels.cycleCriteriaPrompt
              : labels.selectCountTypePrompt}
          </Alert>
        ) : null}
      </Paper>

      <Paper
        elevation={3}
        sx={{
          position: "sticky",
          bottom: 0,
          px: 2.5,
          py: 1.75,
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          zIndex: 100,
          borderTop: "1px solid",
          borderColor: "divider",
          mt: "auto",
          bgcolor: "background.paper",
          borderRadius: 2,
        }}
      >
        {isEdit || isView ? (
          <>
            <Box>
              {(isEdit || isView) && (
                <motion.div
                  whileHover={{ scale: 1.03 }}
                  whileTap={{ scale: 0.97 }}
                  transition={{ type: "spring", stiffness: 300, damping: 22 }}
                >
                  <Button
                    variant="contained"
                    startIcon={<Delete />}
                    sx={ACTION_BUTTON_THEMES.error}
                    onClick={handleDelete}
                  >
                    {labels.deleteConfirm}
                  </Button>
                </motion.div>
              )}
            </Box>
            <Box sx={{ display: "flex", gap: 1.5 }}>
              <motion.div
                whileHover={{ scale: 1.03 }}
                whileTap={{ scale: 0.97 }}
                transition={{ type: "spring", stiffness: 300, damping: 22 }}
              >
                <Button
                  variant="contained"
                  startIcon={<ArrowBackIcon />}
                  onClick={handleBack}
                  sx={ACTION_BUTTON_THEMES.close}
                >
                  {labels.back}
                </Button>
              </motion.div>
              {isEdit && (
                <>
                  <motion.div
                    whileHover={{ scale: 1.03 }}
                    whileTap={{ scale: 0.97 }}
                    transition={{ type: "spring", stiffness: 300, damping: 22 }}
                  >
                    <Button
                      variant="outlined"
                      color="success"
                      startIcon={<CheckCircleOutlineIcon />}
                    >
                      {labels.completeCount}
                    </Button>
                  </motion.div>
                  <motion.div
                    whileHover={{ scale: 1.03 }}
                    whileTap={{ scale: 0.97 }}
                    transition={{ type: "spring", stiffness: 300, damping: 22 }}
                  >
                    <Button variant="outlined" onClick={handleSave}>
                      {labels.save} +
                    </Button>
                  </motion.div>
                </>
              )}
            </Box>
          </>
        ) : (
          <>
            <Typography variant="caption" color="text.secondary">
              {/* <span style={{ color: "red" }}>*</span>{" "}
              {labels.requiredFieldsText} */}
            </Typography>
            <Box sx={{ display: "flex", gap: 1.5 }}>
              <motion.div
                whileHover={{ scale: 1.03 }}
                whileTap={{ scale: 0.97 }}
                transition={{ type: "spring", stiffness: 300, damping: 22 }}
              >
                <Button
                  variant="contained"
                  startIcon={<ArrowBackIcon />}
                  sx={ACTION_BUTTON_THEMES.close}
                  onClick={handleBack}
                >
                  {labels.back}
                </Button>
              </motion.div>
              <motion.div
                whileHover={{ scale: 1.03 }}
                whileTap={{ scale: 0.97 }}
                transition={{ type: "spring", stiffness: 300, damping: 22 }}
              >
                <Button
                  variant="contained"
                  startIcon={<SaveOutlinedIcon />}
                  sx={ACTION_BUTTON_THEMES.success}
                  onClick={handleSave}
                >
                  {labels.save}
                </Button>
              </motion.div>
            </Box>
          </>
        )}
      </Paper>
    </Box>
  );
};

export default Count;
