//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewer
{
    public partial class Default
    {
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlLanding;
        protected global::System.Web.UI.WebControls.Panel pnlFileManager;
        protected global::System.Web.UI.WebControls.LinkButton tabRpt;
        protected global::System.Web.UI.WebControls.LinkButton tabRdlc;
        protected global::System.Web.UI.WebControls.Panel pnlRptTab;
        protected global::System.Web.UI.WebControls.Repeater rptRptFiles;
        protected global::System.Web.UI.WebControls.Panel pnlRptEmpty;
        protected global::System.Web.UI.WebControls.FileUpload fuRptUpload;
        protected global::System.Web.UI.WebControls.Button btnUploadRpt;
        protected global::System.Web.UI.WebControls.Panel pnlRptUploadResult;
        protected global::System.Web.UI.WebControls.Label lblRptUploadResult;
        protected global::System.Web.UI.WebControls.Panel pnlRdlcTab;
        protected global::System.Web.UI.WebControls.Repeater rptRdlcFiles;
        protected global::System.Web.UI.WebControls.Panel pnlRdlcEmpty;
        protected global::System.Web.UI.WebControls.FileUpload fuRdlcUpload;
        protected global::System.Web.UI.WebControls.Button btnUploadRdlc;
        protected global::System.Web.UI.WebControls.Panel pnlRdlcUploadResult;
        protected global::System.Web.UI.WebControls.Label lblRdlcUploadResult;
    }
}
